spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){cyan} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){magenta}%n"

